version: '3.8'
services:
  php:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - 5555:80
    volumes:
        - ./src:/var/www/html
    networks:
     - my-net
  mysql:
    image: mariadb
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: passwords
    command: --init-file /data/application/init.sql
    volumes:
        - ./database/sql/createTable.sql:/data/application/init.sql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 'password'

networks :
  my-net:
    name: my-net
    external: true