version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    image: php:8.0-apache
    volumes:
      - ./app/:/var/www/html/
    ports:
      - 8000:80
  mysql:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: cms
        MYSQL_USER: root
        MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    volumes:
        - ./database/sql/createTable.sql:/data/application/init.sql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 'password'